<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration [
        <!ELEMENT configuration (settings|typeAliases|plugins)*>
        <!ELEMENT settings (setting)*>
        <!ELEMENT setting (#PCDATA)>
        <!ATTLIST setting
                name CDATA #REQUIRED
                value CDATA #REQUIRED>
        <!ELEMENT typeAliases (package)*>
        <!ELEMENT package (#PCDATA)>
        <!ATTLIST package
                name CDATA #REQUIRED>
        <!ELEMENT plugins (plugin)*>
        <!ELEMENT plugin (property)*>
        <!ATTLIST plugin
                interceptor CDATA #REQUIRED>
        <!ELEMENT property (#PCDATA)>
        <!ATTLIST property
                name CDATA #REQUIRED
                value CDATA #REQUIRED>
        ]>
<configuration>
    <settings>
        <!--配置日志打印-->
        <setting name="logImpl" value="STDOUT_LOGGING"/>
    </settings>

    <!--配置包的别名-->
    <typeAliases>
        <package name="com.jbssm.domain"></package>
    </typeAliases>

    <!--配置分页插件pageHelper-->
    <plugins>
    <plugin interceptor="com.github.pagehelper.PageInterceptor">
        <!--reasonable：分页合理化参数，默认值为false。
            当该参数设置为 true 时，pageNum<=0 时会查询第一页，
            pageNum>pages（超过总数时），会查询最后一页。
            默认false 时，直接根据参数进行查询。-->
        <property name="reasonable" value="true"/>
    </plugin>
    </plugins>
</configuration>
